;; Load all necessary files
(load-user-file "main/use-package-setup.el")
(load-user-file "main/melpa-config.el")
(load-user-file "main/global-modes.el")
(load-user-file "main/extra-keybinds.el")
(load-user-file "main/which-key.el")
(load-user-file "main/smooth-scrolling.el")
(load-user-file "main/elcord-setup.el")
(load-user-file "main/ligatures.el")
(load-user-file "main/visual.el")
